version: "3"

dotenv: [".env"]

vars:
  MIGRATION_DSN: "postgres://{{.POSTGRES_USER}}:{{.POSTGRES_PASSWORD}}@{{.POSTGRES_HOST}}:{{.POSTGRES_PORT}}/{{.POSTGRES_DB}}"

tasks:
  migration-up:
    cmds:
      - goose -dir {{.MIGRATION_DIR}} postgres "{{.MIGRATION_DSN}}" up -v

  migration-status:
    cmds:
      - goose -dir {{.MIGRATION_DIR}} postgres "{{.MIGRATION_DSN}}" status -v

  migration-down:
    cmds:
      - goose -dir {{.MIGRATION_DIR}} postgres "{{.MIGRATION_DSN}}" down -v

  generate-auth:
    cmds:
      - |
        protoc \
          --proto_path=protos/proto \
          --go_out=protos/gen/go --go_opt=paths=source_relative \
          --go-grpc_out=protos/gen/go --go-grpc_opt=paths=source_relative \
          protos/proto/auth/v1/auth.proto

  generate-chat:
    cmds:
      - |
        protoc \
          --proto_path=protos/proto \
          --go_out=protos/gen/go --go_opt=paths=source_relative \
          --go-grpc_out=protos/gen/go --go-grpc_opt=paths=source_relative \
          protos/proto/chat/v1/chat.proto
