version: "3"

tasks:
  generate:
    cmds:
      - |
        # auth/v1
        protoc \
          --proto_path=proto \
          --go_out=gen/go --go_opt=paths=source_relative \
          --go-grpc_out=gen/go --go-grpc_opt=paths=source_relative \
          proto/auth/v1/auth.proto
